name: 'Snyk tracking'
description: 'Generate PM issues in GLPI'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  file-path:
    description: 'Path of snyk vulnerabilities file'
    required: true
  issue-tracker:
    description: 'which platform to create issue on'
    required: true
  gh-token:
    description: 'github token for authentication'
    required: false
  repo-info:
    description: 'repo info, format : "owner/repo"'
    required: false


runs:
  using: node20
  main: dist/index.js
