name: 'Snyk tracking'
description: 'Generate PM issues in GLPI'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  file-path:
    description: 'Path of snyk vulnerabilities file'
    required: true

runs:
  using: node20
  main: dist/index.js
